### PR TITLE
WIP: Implement theme system

### PR DESCRIPTION
**Pull request by Tracer1337**
| Status  | Type  |
| :---: | :---: |
| :x: | Feature |

## Description

**WIP, beacuse colors for darkmode are missing. Are they defined already?**

Theme-System through CSS variables. The SCSS variables are references to the css variables now.

Themes are stored in the folder ``src/themes``. The current theme is stored in Redux and can be changed through a Redux action.

## Screenshots / GIFs (if appropriate):

Animation

## Resolves

[frontend/projects/1#card-51929616](https://github.com/vocascan/vocascan-frontend/projects/1#card-51929616)

### CODE REVIEW

**Comment by luwol03** [comment]
Thank you for your long time ago contribution. Because we now decided to leave out tailwindcss from vocascan this PR can actually be continued. Here are just a few things I suggest to change:

- **1** translate the pr title and description to english

- **2** instead of an dark/light theming system we could maybe consider about multiple and also an extendable theme system like vscode have. My thoughts for the future are:
   - **2.1** an key/value store for user settings on the backend where we store which theme a user prefers which can be overwritten per device on localstorage
   - **2.2** . It would also be cool, if we could somehow select a custom css in the desktop app or mount custom themes into the frontend nginx docker container to select.
   - **2.3** Maybe we could consider about dark/light implementation of each theme

**Comment by luwol03** [comment]
Why have you closed this pr?

**Comment by Tracer1337** [comment]
Oh scheiße

**Comment by Tracer1337** [comment]
Hab den PR ausversehen gelöscht

**Comment by luwol03** [comment]
> Oh scheiße

Dont say that.

**Pull request closed without merging**
