### PR TITLE
Fixed dark mode bug

### PR DESCRIPTION
**Pull request by aritroCoder**
| Status  | Type  |
| :---: | :---: |
| :white_check_mark: Ready  | Bug|

Description
Fixed the bug by changing the SCSS color variable used

Motivation and Context
Now the nav header is visible in dark mode

Screenshots / GIFs (if appropriate):
Screenshot from 2022-09-29 17-19-52

Checklist
 [x]I have read the CONTRIBUTING document.
 [x]I have considered the accessibility of my changes (i.e. did I add proper content descriptions to images, or run my changes with talkback enabled?)
 [x]I have documented my code if needed
Resolves
issue https://github.com/vocascan/vocascan-frontend/issues/130

### CODE REVIEW

**Comment by noctera** [comment]
@aritroCoder Now you deleted the whole package-lock.json. You only had to delete your own changes in it.

Could you please fix this, so you don't have any modifications in the package-lock.json?

**Comment by aritroCoder** [comment]
I think its done now

**Comment by Tracer1337** [comment]
Please also provide a screenshot of how the changes affect the dark-theme. If both look good, this can be merged

**Comment by aritroCoder** [comment]
> Please also provide a screenshot of how the changes affect the dark-theme. If both look good, this can be merged

image

**Comment by noctera** [comment]
Looks good to me. This can be merged

**Review by noctera — APPROVED** [review]

**Comment by aritroCoder** [comment]
please add the `hacktobefest accepted` label so that it will count toward my progress

**Pull request merged**
